spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1


server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"



