server:
  port: 8090
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: server-consumer
          uri: http://localhost:8080
          predicates:
            - Path=/feign/**
#        load balance
        - id: service-consumer-load-balance
          uri: lb://server-consumer
          predicates:
            - Path=/echo/**